"""Final Layer 2R qualitative comparison figures.

Purpose
-------
Reproduce the deterministic per-case figure generated by the authoritative
Layer 2R 40-case formal run in notebook cells 109 and 110.

Inputs and outputs
------------------
The figure functions accept eight aligned three-dimensional ``[Z, H, W]``
arrays: normalized current T1c MRI, future-change target, fixed-baseline
probability, three EIA probability maps, the EIA morphology output, and the
PCC probability map. ``make_layer2r_formal_figure`` returns the matplotlib
figure and selected slice. ``save_layer2r_formal_figure`` writes the formal
PNG-style output and returns its path.

Dependencies
------------
NumPy and matplotlib only. Callers performing headless rendering must select
a non-interactive matplotlib backend before importing ``matplotlib.pyplot``.

Scientific assumptions
----------------------
Inputs have already been loaded, oriented, normalized, and calculated by the
earlier migration orders. This module does not transpose, clip, normalize,
threshold, infer, or evaluate them. In particular, probability panels retain
the notebook's independent matplotlib autoscaling.

Expected behaviour
------------------
The target slice has the greatest future-change target area, with NumPy's
first-maximum tie rule. The panel order, titles, colour maps, 18-by-8-inch
layout, tight layout, 150 DPI, tight export bounding box, and figure closing
match the final formal notebook cells.

Known limitations
-----------------
The notebook supplies no orientation labels or colour bars. Independently
autoscaled probability panels can look comparable even when their absolute
ranges differ. Empty targets select the middle slice in the helper, although
the formal experiment rejected such cases before figure construction.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.figure import Figure


FIGURE_SIZE = (18, 8)
FIGURE_DPI = 150
PANEL_TITLES = (
    "Current T1c",
    "Target",
    "Fixed baseline",
    "EIA-linear",
    "EIA-blend-0.90",
    "EIA-blend-0.75",
    "EIA-morph",
    "PCC",
)
PANEL_CMAPS = (
    "gray",
    "gray",
    "hot",
    "hot",
    "hot",
    "hot",
    "gray",
    "hot",
)


def choose_target_slice(target: np.ndarray) -> int:
    """Select the formal notebook's maximum-target-area Z slice."""
    per_slice = target.astype(bool).sum(axis=(1, 2))
    if per_slice.max() > 0:
        return int(np.argmax(per_slice))
    return int(target.shape[0] // 2)


def _validate_aligned_zhw(arrays: tuple[np.ndarray, ...]) -> None:
    """Require the complete formal panel set to be aligned 3D volumes."""
    shapes = [np.asarray(array).shape for array in arrays]
    if any(len(shape) != 3 for shape in shapes):
        raise ValueError(f"Expected 3D [Z, H, W] arrays, got shapes {shapes}")
    if any(shape != shapes[0] for shape in shapes[1:]):
        raise ValueError(f"Expected aligned arrays, got shapes {shapes}")


def make_layer2r_formal_figure(
    current_t1c: np.ndarray,
    target: np.ndarray,
    fixed_baseline: np.ndarray,
    eia_linear: np.ndarray,
    eia_blend090: np.ndarray,
    eia_blend075: np.ndarray,
    eia_morph: np.ndarray,
    pcc: np.ndarray,
) -> tuple[Figure, int]:
    """Build the final formal Layer 2R per-case comparison figure."""
    arrays = (
        current_t1c,
        target,
        fixed_baseline,
        eia_linear,
        eia_blend090,
        eia_blend075,
        eia_morph,
        pcc,
    )
    _validate_aligned_zhw(arrays)
    z = choose_target_slice(target)

    fig, axes = plt.subplots(2, 4, figsize=FIGURE_SIZE)
    axes = axes.ravel()

    vis_items = (
        ("Current T1c", current_t1c[z], "gray"),
        ("Target", target[z].astype(float), "gray"),
        ("Fixed baseline", fixed_baseline[z], "hot"),
        ("EIA-linear", eia_linear[z], "hot"),
        ("EIA-blend-0.90", eia_blend090[z], "hot"),
        ("EIA-blend-0.75", eia_blend075[z], "hot"),
        ("EIA-morph", eia_morph[z], "gray"),
        ("PCC", pcc[z], "hot"),
    )

    for ax, (title, image, cmap) in zip(axes, vis_items):
        ax.imshow(image, cmap=cmap)
        ax.set_title(title, fontsize=10)
        ax.axis("off")

    plt.tight_layout()
    return fig, z


def save_layer2r_formal_figure(
    output_path: str | Path,
    current_t1c: np.ndarray,
    target: np.ndarray,
    fixed_baseline: np.ndarray,
    eia_linear: np.ndarray,
    eia_blend090: np.ndarray,
    eia_blend075: np.ndarray,
    eia_morph: np.ndarray,
    pcc: np.ndarray,
) -> Path:
    """Save and close one final formal Layer 2R comparison figure."""
    path = Path(output_path)
    fig, _ = make_layer2r_formal_figure(
        current_t1c,
        target,
        fixed_baseline,
        eia_linear,
        eia_blend090,
        eia_blend075,
        eia_morph,
        pcc,
    )
    plt.savefig(path, dpi=FIGURE_DPI, bbox_inches="tight")
    plt.close(fig)
    return path
